# Generated by Django 5.0.3 on 2024-04-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_author',
            new_name='album_musician',
        ),
    ]
