# Generated by Django 5.0.3 on 2024-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
                ('binary_field', models.BinaryField(max_length=5)),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
            ],
        ),
    ]
