# Generated by Django 5.0.3 on 2024-03-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('task_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='categories.category')),
            ],
        ),
    ]
